In [3]:
#Import csv file from DSPM website, label column names and parse date format:
import pandas as pd
sales=pd.read_csv("http://liacs.leidenuniv.nl/~takesfw/DSPM/data/sales.csv", names=["saleId", "saleDateTime", "accountName", "coins", "currency", "priceInCurrency", "priceInEUR", "methodId", "ip", "ipCountry"], parse_dates=["saleDateTime"])

In [5]:
#Sort original csv file dates
sales = sales.sort_values(["saleDateTime"])

In [165]:
first = sales.groupby("accountName")["saleDateTime"].nsmallest(2)

In [139]:
last = sales.groupby("accountName")["saleDateTime"].nlargest(2)

In [180]:
firstamount = sales.groupby("accountName")['priceInEUR'].tail()
firstamount1 = firstamount.sum()
firstamount

0         10.000000
5         10.000000
6         10.000000
15        10.000000
17        20.000000
21        10.000000
24        20.000000
25         5.000000
30        10.000000
31        10.000000
34        10.000000
40        20.000000
43        20.000000
46        10.000000
47        10.000000
48        10.000000
49        15.000000
52        20.000000
54         1.000000
56        10.000000
60        20.000000
61         5.000000
69        20.000000
70         5.000000
73        20.000000
74         5.000000
76        10.000000
77        30.000000
78         2.000000
79        20.000000
            ...
747079    22.232000
747080     2.000000
747081     3.706000
747082     8.000000
747083     8.000000
747084     8.000000
747085    50.000000
747086     4.000000
747087     2.000000
747088     2.000000
747089     8.000000
747090     8.000000
747093     2.820270
747094     1.690000
747095    30.000000
747096     1.175113
747097     8.000000
747098     1.690000
747099     1.690000
747100     1.690000
747101     1.690000
747102     1.690000
747103     1.690000
747104     2.000000
747105     4.000000
747106     2.000000
747107     4.000000
747108     1.228000
747109     4.000000
747110    10.000000
Name: priceInEUR, Length: 229350, dtype: float64

In [ ]:
lastamount

In [164]:
def functie(x):
    q = True
    if x.iloc[0]['First'] > x.iloc[0]['Last']:
        q = False
    
    return q

#temp1 = sales.groupby("accountName")["ipCountry"].nunique()
#temp2 = sales.groupby("accountName")["saleDateTime"].max() - sales.groupby("accountName")["saleDateTime"].min()
#temp3 = sales.groupby("accountName")["priceInEUR"].sum()
#temp4 = sales.groupby("accountName")["saleId"].nunique()
#tempx = sales.groupby("accountName")["ipCountry"].value_counts()
#temp5 = tempx.groupby("accountName").idxmax()
#tempy = sales.groupby("accountName")["methodId"].value_counts()
#temp6 = tempy.groupby("accountName").idxmax()

#temp7
df = pd.DataFrame()
df['First'] = abs(first.diff().reset_index().groupby("accountName").tail(1).set_index("accountName")["saleDateTime"].dt.days)
df['Last'] = abs(last.diff().reset_index().groupby("accountName").tail(1).set_index("accountName")["saleDateTime"].dt.days)
temp7 = df.groupby("accountName").apply(functie)

#temp8
df = pd.DataFrame()
df['First'] = abs(first.diff().reset_index().groupby("accountName").tail(1).set_index("accountName")["saleDateTime"].dt.days)
df['Last'] = abs(last.diff().reset_index().groupby("accountName").tail(1).set_index("accountName")["saleDateTime"].dt.days)
temp7 = df.groupby("accountName").apply(functie)

#tempi = abs(first.diff().reset_index().groupby("accountName").tail(1).set_index("accountName")["saleDateTime"].dt.days)
#tempj = abs(last.diff().reset_index().groupby("accountName").tail(1).set_index("accountName")["saleDateTime"].dt.days)
#tempj
sales.loc[sales["accountName"] == "000113b526fbc8d19f03fccb9"]

,saleId,saleDateTime,accountName,coins,currency,priceInCurrency,priceInEUR,methodId,ip,ipCountry
292569,1678821,2013-07-23 06:19:11,000113b526fbc8d19f03fccb9,6100,EUR,8.0,8.0,2000,173.126.58.11,FR
292582,1678853,2013-07-23 06:53:40,000113b526fbc8d19f03fccb9,3000,EUR,4.0,4.0,2000,173.126.58.11,FR
329861,1774587,2013-09-27 12:41:33,000113b526fbc8d19f03fccb9,2000,EUR,2.0,2.0,2000,149.233.143.79,FR

In [136]:
customers = pd.DataFrame()
customers['countries'] = temp1
customers['lifespan'] = temp2
customers['lifetime_spend'] = temp3
customers['lifetime_trans'] = temp4
customers['fav_country'] = temp5
customers['fav_paymethod'] = temp6

customers

,countries,lifespan,lifetime_spend,lifetime_trans,fav_country,fav_paymethod
accountName,,,,,,
000113b526fbc8d19f03fccb9,1,66 days 06:22:22,14.000,3,"(000113b526fbc8d19f03fccb9, FR)","(000113b526fbc8d19f03fccb9, 2000)"
00027408fd5b8ff231814dbf2,1,27 days 15:43:48,431.780,120,"(00027408fd5b8ff231814dbf2, FR)","(00027408fd5b8ff231814dbf2, 2000)"
0002c9dd969f5e5831d492524,1,83 days 09:35:55,40.000,5,"(0002c9dd969f5e5831d492524, NL)","(0002c9dd969f5e5831d492524, 30)"
0004dd02811925311678f7c85,1,0 days 23:26:42,21.690,5,"(0004dd02811925311678f7c85, FR)","(0004dd02811925311678f7c85, 2000)"
00066a451be9a6bc5fda16fd9,1,76 days 20:48:49,24.050,17,"(00066a451be9a6bc5fda16fd9, PL)","(00066a451be9a6bc5fda16fd9, 2000)"
0006801dfc7f8d682dd1b2b23,1,0 days 00:11:35,9.622,2,"(0006801dfc7f8d682dd1b2b23, AU)","(0006801dfc7f8d682dd1b2b23, 1000)"
000697979068d5bbc49dbbd64,1,0 days 00:00:00,10.000,1,"(000697979068d5bbc49dbbd64, US)","(000697979068d5bbc49dbbd64, 137)"
0006a7e0deb474b2c0339f38e,1,162 days 05:25:10,100.000,11,"(0006a7e0deb474b2c0339f38e, IT)","(0006a7e0deb474b2c0339f38e, 40)"
00081bff5faac28727d229ab2,1,0 days 00:00:00,10.000,1,"(00081bff5faac28727d229ab2, PR)","(00081bff5faac28727d229ab2, 40)"
0008709e543fee1af42062b9c,1,228 days 00:23:03,57.000,6,"(0008709e543fee1af42062b9c, BE)","(0008709e543fee1af42062b9c, 80)"
0008c60a0381b4bcc793436fd,1,89 days 22:21:33,13.612,4,"(0008c60a0381b4bcc793436fd, GB)","(0008c60a0381b4bcc793436fd, 1000)"
000b49aef4fdca6601be00775,1,518 days 17:58:03,95.000,10,"(000b49aef4fdca6601be00775, DE)","(000b49aef4fdca6601be00775, 40)"
000ba55fec599714628aa4e3b,1,457 days 21:22:40,45.000,2,"(000ba55fec599714628aa4e3b, DE)","(000ba55fec599714628aa4e3b, 40)"
000e9e31fa555ca178e7ab025,2,50 days 06:15:13,26.900,15,"(000e9e31fa555ca178e7ab025, FR)","(000e9e31fa555ca178e7ab025, 2000)"
000f5355d1554ff0bf926d6ab,1,9 days 17:39:58,27.880,12,"(000f5355d1554ff0bf926d6ab, DE)","(000f5355d1554ff0bf926d6ab, 1000)"
000f831d32866742c0c93e1e7,1,0 days 00:00:00,10.000,1,"(000f831d32866742c0c93e1e7, GR)","(000f831d32866742c0c93e1e7, 40)"
0014881dea8cdbf6fdc3dc8e1,1,10 days 19:27:12,17.380,6,"(0014881dea8cdbf6fdc3dc8e1, MQ)","(0014881dea8cdbf6fdc3dc8e1, 2000)"
001820ed18e2e5987810cc1da,2,19 days 01:50:40,44.450,14,"(001820ed18e2e5987810cc1da, FR)","(001820ed18e2e5987810cc1da, 2000)"
0018467de4d5cee6685cda843,1,283 days 07:19:46,67.070,18,"(0018467de4d5cee6685cda843, RE)","(0018467de4d5cee6685cda843, 2000)"
001879062f1b4dea3719de128,1,0 days 00:00:00,25.000,1,"(001879062f1b4dea3719de128, NL)","(001879062f1b4dea3719de128, 30)"
0018ef6545d446d90df80a0d0,1,29 days 03:30:50,7.000,2,"(0018ef6545d446d90df80a0d0, GR)","(0018ef6545d446d90df80a0d0, 40)"
001987562fccee7fe4eb20f0c,1,172 days 11:28:59,7.970,3,"(001987562fccee7fe4eb20f0c, DE)","(001987562fccee7fe4eb20f0c, 1000)"
001998acd85a26524fbdf22f9,1,0 days 00:00:43,14.822,2,"(001998acd85a26524fbdf22f9, MQ)","(001998acd85a26524fbdf22f9, 2000)"
0019ab20f5a35f0510524aaee,1,0 days 00:00:00,30.000,1,"(0019ab20f5a35f0510524aaee, NL)","(0019ab20f5a35f0510524aaee, 30)"
001a811d118a37c5e56633234,1,167 days 22:00:59,2.980,2,"(001a811d118a37c5e56633234, DE)","(001a811d118a37c5e56633234, 1000)"
001bbecce468a9141c54e1f12,1,0 days 00:00:00,1.990,1,"(001bbecce468a9141c54e1f12, DE)","(001bbecce468a9141c54e1f12, 1000)"
001c238e6f4fec64022163074,1,0 days 00:00:00,2.480,1,"(001c238e6f4fec64022163074, RO)","(001c238e6f4fec64022163074, 1000)"
001d1c82b868b95c7c6df156a,1,0 days 00:00:00,10.000,1,"(001d1c82b868b95c7c6df156a, GB)","(001d1c82b868b95c7c6df156a, 20)"
001e01b2326898069d59344a0,1,0 days 00:07:23,8.632,2,"(001e01b2326898069d59344a0, PL)","(001e01b2326898069d59344a0, 1000)"
001f56848117e34c5c3a025ec,1,63 days 14:09:08,19.683,4,"(001f56848117e34c5c3a025ec, SE)","(001f56848117e34c5c3a025ec, 1000)"
...,...,...,...,...,...,...
ffe8e4e285e4aca8e01256df4,1,3 days 09:49:32,23.429,2,"(ffe8e4e285e4aca8e01256df4, TR)","(ffe8e4e285e4aca8e01256df4, 1000)"
ffe9ac7f50f1acfb230d3fbd1,2,32 days 03:57:44,97.380,37,"(ffe9ac7f50f1acfb230d3fbd1, FR)","(ffe9ac7f50f1acfb230d3fbd1, 2000)"
ffeaa2d05f322212f85f5988f,2,136 days 05:00:23,355.000,31,"(ffeaa2d05f322212f85f5988f, CY)","(ffeaa2d05f322212f85f5988f, 40)"
ffebce198cccc40f6275680bc,1,590 days 06:44:25,270.000,12,"(ffebce198cccc40f6275680bc, DE)","(ffebce198cccc40f6275680bc, 20)"
ffec460ee76623fe1108a9ce5,1,398 days 18:35:52,33.500,4,"(ffec460ee76623fe1108a9ce5, FR)","(ffec460ee76623fe1108a9ce5, 1000)"
ffed3e0efe2e9a39b429cfbbb,1,636 days 11:31:31,124.740,126,"(ffed3e0efe2e9a39b429cfbbb, VE)","(ffed3e0efe2e9a39b429cfbbb, 1000)"
ffedbf6423c11b30e12f29dec,2,206 days 12:56:20,190.690,32,"(ffedbf6423c11b30e12f29dec, FR)","(ffedbf6423c11b30e12f29dec, 2000)"
ffeea3174463ede2f29d543ae,1,0 days 00:00:00,5.000,1,"(ffeea3174463ede2f29d543ae, LU)","(ffeea3174463ede2f29d543ae, 40)"
ffef6877a5bf334b0f72d2dab,1,124 days 21:11:16,515.950,20,"(ffef6877a5bf334b0f72d2dab, DE)","(ffef6877a5bf334b0f72d2dab, 1000)"
fff037eb31502c0d7ac9be968,1,1 days 05:08:38,16.000,4,"(fff037eb31502c0d7ac9be968, BE)","(fff037eb31502c0d7ac9be968, 1000)"
fff1926e114083fa03aaad54e,1,0 days 13:30:15,18.600,2,"(fff1926e114083fa03aaad54e, RO)","(fff1926e114083fa03aaad54e, 1000)"
fff19edea1f8eba9265912a40,1,61 days 01:30:30,199.690,25,"(fff19edea1f8eba9265912a40, FR)","(fff19edea1f8eba9265912a40, 1000)"
fff249a4834b795a5077d0c4c,1,61 days 21:59:18,68.450,14,"(fff249a4834b795a5077d0c4c, FR)","(fff249a4834b795a5077d0c4c, 2000)"
fff25cbc38bb31a180809b05c,2,273 days 00:58:59,40.000,4,"(fff25cbc38bb31a180809b05c, DE)","(fff25cbc38bb31a180809b05c, 40)"
fff34988f516f4c17e84fdc6c,1,17 days 21:22:00,2.637,2,"(fff34988f516f4c17e84fdc6c, PL)","(fff34988f516f4c17e84fdc6c, 1000)"
fff3597b7ff85e6ef60ccf26a,1,2 days 00:51:53,17.830,9,"(fff3597b7ff85e6ef60ccf26a, FR)","(fff3597b7ff85e6ef60ccf26a, 2000)"
fff44d0985646f6e196b7aa3c,1,29 days 05:42:51,14.436,8,"(fff44d0985646f6e196b7aa3c, PL)","(fff44d0985646f6e196b7aa3c, 2000)"
fff46c4ad99552dba7ec0765d,1,28 days 17:11:15,35.000,3,"(fff46c4ad99552dba7ec0765d, DE)","(fff46c4ad99552dba7ec0765d, 139)"
fff4b42bf276ae64b38035bc0,3,359 days 12:11:30,236.140,58,"(fff4b42bf276ae64b38035bc0, RE)","(fff4b42bf276ae64b38035bc0, 2000)"
fff6413b2530563b24f2e2cde,1,40 days 14:02:33,24.000,7,"(fff6413b2530563b24f2e2cde, PT)","(fff6413b2530563b24f2e2cde, 1000)"
fff7bd9e5cb6846b89354d022,1,43 days 12:24:21,8.000,3,"(fff7bd9e5cb6846b89354d022, PT)","(fff7bd9e5cb6846b89354d022, 1000)"
fff836cc162e21cdbba10feb1,1,85 days 01:10:10,26.000,4,"(fff836cc162e21cdbba10feb1, PT)","(fff836cc162e21cdbba10feb1, 40)"
fff8450fcbc698f4d61ab331c,1,0 days 00:00:00,10.000,1,"(fff8450fcbc698f4d61ab331c, DE)","(fff8450fcbc698f4d61ab331c, 40)"
fff84b33ff8f662f6d01e9c64,1,54 days 05:32:10,5.858,4,"(fff84b33ff8f662f6d01e9c64, SE)","(fff84b33ff8f662f6d01e9c64, 1000)"
fff8cc5339049bf6ef2e50780,1,1179 days 04:00:10,104.000,15,"(fff8cc5339049bf6ef2e50780, GR)","(fff8cc5339049bf6ef2e50780, 40)"
fffaa6a39be1ab2f86fd2571f,1,0 days 00:00:00,24.913,1,"(fffaa6a39be1ab2f86fd2571f, GB)","(fffaa6a39be1ab2f86fd2571f, 1000)"
fffb2efd72b3318b86173d294,1,0 days 00:00:00,8.000,1,"(fffb2efd72b3318b86173d294, MQ)","(fffb2efd72b3318b86173d294, 2000)"
fffcd5cce92731953647fe62f,3,685 days 03:17:42,564.969,139,"(fffcd5cce92731953647fe62f, GP)","(fffcd5cce92731953647fe62f, 2000)"
fffd3e63c839efd5435be9619,1,0 days 00:48:34,24.660,2,"(fffd3e63c839efd5435be9619, CH)","(fffd3e63c839efd5435be9619, 1000)"
fffdb7a076319ce6d46ec4ed8,1,28 days 20:36:56,38.690,8,"(fffdb7a076319ce6d46ec4ed8, FR)","(fffdb7a076319ce6d46ec4ed8, 2010)"